local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>ff', builtin.find_files, { desc = "Find files" })
vim.keymap.set('n', '<leader>fg', builtin.live_grep, { desc = "Live grep" })
vim.keymap.set('n', '<leader>fb', builtin.buffers, { desc = "Buffers" })
vim.keymap.set('n', '<leader>fm', builtin.marks, { desc = "Marks" })
vim.keymap.set('n', '<leader>fr', builtin.registers, { desc = "Registers" })
vim.keymap.set('n', '<leader>fc', function() builtin.colorscheme({ enable_preview = true }) end, { desc = "Colorschemes" })
vim.keymap.set('n', '<leader>fM', builtin.man_pages, { desc = "Man pages" })
vim.keymap.set('n', '<leader>fh', builtin.help_tags, { desc = "Help tags" })
